### ISSUE TITLE
Looser (or user-defined) tolerance for geometry optimization

### ISSUE THREAD

**Issue by amcisaac** [openforcefield/yammbs#30]
Would it be possible to either loosen the default tolerance for geometry minimization convergence, and/or add an optional parameter to allow a user-defined convergence tolerance? Right now the default seems to be 5e-9 kJ/nm/mol, which seems really tight. I think this is inherited from our older benchmarking code, and results from a documentation issue in OpenMM, where they used to say this was an energy tolerance, but it's actually a force tolerance. I've found that OpenMM's default of 10 kJ/nm/mol produces MM-optimized structures that agree much better with the QM parent structure.

**Comment by mattwthompson** [comment]
I think you're right about the energy/force error in documentation. I have no memory of writing these lines anew, so yeah they're probably inherited 

https://github.com/mattwthompson/ib/blob/77cb48573dd496b7bfeb9ce3200ef036976bac9b/ibstore/_minimize.py#L185


Changing the default(s) should be easy, but I have a scientific question I can't get out of my head.

Are you also messing around with the maximum number of iterations? It looks to me like passing `(5e-9, 1500)` makes it run to nearly zero in energy/force, so either
* It's usually quitting at 1500 steps (the default is `maxIterations=0`)
* You're finding more MM energy minimization produces structures that agree less with the QM reference

Any idea what I'm missing here?

**Comment by amcisaac** [comment]
I am not passing `maxIterations` with the looser threshold, so I believe it should just be running until it converges. 

I looked through a couple of the cases where there are discrepancies, and for the tighter threshold, it looks like it is usually quitting at 1500 steps _and_ running for longer is leading to less agreement with the QM reference. This was the subject of some discussion at one of the recent FF fitting meetings, with the conclusion being a hypothesis that the PES is pretty flat, so causing it to finish with a very tight convergence threshold might just be sending it off to bounce around the flat part without much information and it winds up somewhere far away when it should have just been cut off earlier. However, I suppose it is also possible (more likely?) that we are just truncating the optimization earlier which leads to closer agreement with the starting structure. 

To determine which of these situations is more likely, I'm trying to inspect the minimization trajectory using the `MinimizationReporter` feature in OpenMM. This seems to suggest the PES is very flat, although there are a lot of caveats in the documentation for the `MinimizationReporter` so I'm not 100% sure that I'm interpreting the results correctly. If the landscape is just really flat, I think that's an argument to use a looser convergence (perhaps the default), but if we're just truncating early, we should probably keep it tighter (though 5e-9 is probably too tight and just leading it to quit at 1500 iterations).

**Comment by mattwthompson** [comment]
> However, I suppose it is also possible (more likely?) that using the default convergence is just truncating the optimization earlier which leads to closer agreement with the starting structure.

Thanks - this detail helped me understand the this situation better - I forgot that the MM optimizations use the QM structure as a starting point, otherwise it doesn't make much sense that _less optimization gets you _closer_ to the reference structure. That's what I was getting tripped up on.

I've never done a deep dive on energy minimization, but from the cheap seats it sure looks like a tricky problem to get a handle on. My only idea, and it's not very good since it'd require more work, is switching from OpenMM to geomeTRIC as the minimization engine. If that's a path you want to go down I can look at refactoring the code to switch between those.

And just to make the responsibilities here clear, we'll make these settings whatever you/you and the science team think they should be. In #31 I just flipped them back to the defaults; we can switch them to whatever you want, including passing the tolerance and/or number of iterations through `optimize_mm` as optional arguments[^1]. Just let me know what you decide and we'll go from there.

[^1]: The main caveat here is that the same options would probably need to apply to the _all_ minimizations of a particular dataset + force field combination, anything more granular might be tricky

**Comment by mattwthompson** [comment]
In our meeting today we decided
* Using the defaults is best now
* In the future it might be useful to pass these through as options. but that faces the complication of QM conformer + force field combinations not producing unique MM conformers and energies, which much of the code assumes. So that's pushed off into an idea for the future.

**Comment by amcisaac** [comment]
After doing some more investigation (I looked at about 10 conformers whose structure changed substantially depending on the optimization cutoff), I do believe that the looser cutoff is converging to the local minimum corresponding to the starting structure, and not just cutting off the optimization early. In contrast, the tighter cutoff leads it to continue optimizing on a pretty flat PES and leads to a more global minimum but one that represents a totally different conformer and thus isn't really of use to us for benchmarking purposes. 

Here's an example conformer, with the left being the QM starting structure, center is the Sage 2.1.0-minimized structure using the default convergence cutoff, and the right is using 5e-9 as the convergence cutoff. Note the different orientation of the side chain on the left of the molecule.
![ib_structs](https://github.com/openforcefield/yammbs/assets/29759281/00f78d29-708e-4a6f-bce0-d335d43fcd26)

From looking at the output of the tight-convergence optimization below (left is energy, right is RMS gradient), you can see that it is finding a local minimum and then just wandering around the flat energy surface until it finds a more global minimum. It also doesn't usually converge, just stops at 1500 steps. I also looked at a few with a looser-but-still-tight threshold of 1e-2, which led to basically the same result as 5e-9.
![ib_opt](https://github.com/openforcefield/yammbs/assets/29759281/d04d864a-dd4c-4bca-b84a-8e7f5d111b16)

Since the goal of the minimization is to find the local minimum on the MM surface that best corresponds to the QM starting conformer, I think we want to just stick to the default convergence of 10 kJ/mol/nm

**Comment by mattwthompson** [comment]
That is super illuminating - 10 seems like an arbitrary force to optimize to, but it sure seems to produce great results. it'd be great to capture that in a blog post or docs sometime

**Comment by amcisaac** [comment]
Yeah, I don't know how they arrived at that...I tried a few with a cutoff of 5 and it usually agreed with the cutoff of 10, but anything lower wound up going to a more global solution. I'll certainly write it up on confluence, a blog post would also be interesting!

**Comment by amcisaac** [comment]
Actually, it looks like 10 is tighter than Gaussian (and GeomeTRIC) use for RMS gradient: https://geometric.readthedocs.io/en/latest/options.html#optimization-parameters

3e-4 Ha/Bohr * 2600 kJ/mol / Ha * 1 Bohr/0.0529 nm = 14.74 kJ/mol/nm

So I think this is very well justified.
